AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for id_matching

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  IdMatchingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Role: # Add Role      
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./id_matching
      DockerTag: python3.9-v1

Outputs:
  IdMatchingFunction:
    Description: "IdMatchingFunction ARN"
    Value: !GetAtt IdMatchingFunction.Arn